# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1942f62329d5d1aa720fcb4f2821b6c1011b84636e851ca984637262e9473d57edd7f89904657406b4e54d2d8fb3f5a24c2cd2e6f1a17526e3f8406156c8281f

test:
  secret_key_base: 1d189588873309f8826564cda3dda0ac526a4112cdba6b5e296556ce27af282dc657fb68eb654cb91bb76b57ea08e3af3aa5197f15eca20e1067da13d077df8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
